services:
  frontend:
    build: ./services/frontend
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    env_file:
      - ./services/frontend/.env.local

  redis:
    image: redis:7
    container_name: redis
    networks:
      - app-net
    volumes:
      - redis-data:/data

  gateway:
    build: ./services/api-gateway
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - backend
    env_file:
      - ./services/api-gateway/.env
    networks:
      - app-net

  backend:
    build:
      context: ./services/backend
    volumes:
      - ./services/backend:/app
    networks:
      - app-net

volumes:
  redis-data:

networks:
  app-net:
    driver: bridge
    internal: false